#!/usr/bin/env bash
# Install nginx and start it
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'

# Set ownership of website files
sudo chown -R $USER:$USER /var/www/html

# Configure redirection
sed -i '37i\rewrite ^/redirect_me https://www.github.com/digreatbrian permanent;' /etc/nginx/sites-available/default

# Restart nginx
service nginx restart