#!/usr/bin/env bash
# Install nginx and start it
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

#Give the user  ownership to website files
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www

# Redirect to /redirect_me to github
sed -i '37i\rewrite ^/redirect_me https://www.github.com/digreatbrian permanent;' /etc/nginx/sites-available/default

service nginx start