#!/usr/bin/env bash
# Create a script to install and configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Install and configure HAproxy
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  digreatbrian-frontend
        bind *:80
        mode http
        default_backend digreatbrian-backend
backend digreatbrian-backend
        balance roundrobin
        server 474794-web-01 54.160.127.97:80 check
        server 474794-web-02 54.197.118.110:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
