#!/usr/bin/env bash
# Script that displays Best School 10 times and then displays hi after the 9th recurrence using while loop

i=1

while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    ((i++))
done
