#!/usr/bin/env bash
# run apache on the designated container
# Create a custom index.html file
echo "Hello Holberton!" > /var/www/html/index.html

# Start Apache service
service apache2 start && 'echo apache2 is running'
